In [1]:

import numpy as np
from scipy import linalg
import testalg

num_dim=1   # no. of examples of different dimensions
dim_egs=np.array([5])  # dimension of examples
num_data_pts=np.array([40])
num_k_values=1    
k_values=np.array([2]) 
s0_values=2*np.ones(num_dim,dtype=int) # no. of nonzero values in b0
num_instances=1           # no. of instances to run for each example
alg_flag=np.array([1, 0]) # =1 include in testing, =0 do not include  
num_alg=1
b0_type=1   # to generate the true coefficient vector b0

# initialize the arrays to save the final output
rss=np.zeros( (num_dim*num_k_values,num_alg) )
cpu_time=np.zeros( (num_dim*num_k_values,num_alg) )
num_iter=np.zeros( (num_dim*num_k_values,num_alg) )
stop_flag=-1*np.zeros( (num_dim*num_k_values,num_alg) )
for i in range(num_dim):

    p=dim_egs[i]
    n=num_data_pts[i]
    mu=np.zeros(p)
    sigma=np.eye(p)
    s0=s0_values[i]
    if b0_type==1: # example 1
        b0=np.zeros(p)
        i0=np.ceil(np.linspace(0,p,num=s0,endpoint=False)).astype(int) # get s0 evenly spaced indices, round the next integer if needed
        b0[i0]=1 
    elif b0_type==2: # example 2
        b0=np.zeros(p)
        b0[0:s0]=1 # make first s0 entries 1
    elif b0_type==3: # example 3
        b0=np.zeros(p)   
        i0 = np.random.randint(0,p,s0).astype(int) # pick s0 random indices to make nonzero
        j0 = np.random.randint(1,5,s0) # pick s0 random integers b/w 1 and 5
        b0[i0]=j0

    b0 = np.reshape(b0, (-1,1)) # make it a col array
    
    # run the algorithms and save the output
    for j in range(num_k_values): # for each k value, run the alg
        
        k = k_values[j]
        stop_flag_each_alg, cpu_time_each_alg, rss_each_alg=testalg.main(p,n,k,b0,mu,sigma,num_instances,num_alg,alg_flag)
        rss[j+i*num_k_values,:]=rss_each_alg
        cpu_time[j+i*num_k_values,:]=cpu_time_each_alg
        stop_flag[j+i*num_k_values,:]=stop_flag_each_alg

    # save the output in .pkl file
    print('sol:',rss)
        
        

A,b,c: [[ 2.         -0.04077954 -0.06682397  0.5905683  -0.57211021]
 [-0.04077954  2.          0.36879202  0.06708566  0.08059523]
 [-0.06682397  0.36879202  2.         -0.14214252  0.38348001]
 [ 0.5905683   0.06708566 -0.14214252  2.          0.25905741]
 [-0.57211021  0.08059523  0.38348001  0.25905741  2.        ]] [[-2.12619876]
 [-1.57662581]
 [ 1.13558195]
 [-1.53286316]
 [-0.23592484]] [[30.82813471]]
p,k= 5 2
x0,fx0: [[1.07962175]
 [0.81032614]
 [0.        ]
 [0.        ]
 [0.        ]] 29.041598939543793
ipiv0: [0 2 1 3 4]
ipiv1: []
npiv0, npiv00: 5 5
CE0: [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-5.43035238e-01  1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 8.81322496e-02  1.93658945e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 1.94871283e-01 -1.25460389e+00 -4.66088101e+00  1.00000000e+00
   0.00000000e+00]
 [-1.42996926e+00  6.55322232e+00  9.94907999e+00 -1.90113346e+00
   1.00000000e+00]
