In [1]:
import numpy as np


n1,n2,p,r,n = 2, 2, 5, 5, 10 
Y=np.array([1, 1, 0, 2, 2],dtype=int) 
X=[[ 1.,          0.,          0.,          0.,          0.        ],
 [-0.35485915,  1. ,         0. ,         0.,          0.        ],
 [ 0.73900147, -3.06739299,  1. ,         0.,          0.        ],
 [-0.41936066,  2.07954916, -2.48001176,  1.,          0.        ],
 [ 0.8629648 , -5.26684888,  6.07259163, -2.00029337,  1.        ],
 [-0.39781133,  4.37513021,  1.95567188, -1.20511879,  2.90818423],
 [-1.23775551,  0.96738502, -6.00479805,  2.36192321, -6.35576004],
 [ 1.26812186, -6.24255548,  2.10212715, -0.22108135,  0.78150706],
 [-2.21902784, 12.69620805, -3.64714684,  0.1774518 ,  3.02428501],
 [ 0.75872635, -6.54147509,  1.001566 ,  -0.1128815,  -1.35821625]] 
CE0=[[ 1.,          0.     ,     0.    ,      0.   ,       0.        ],
 [-0.35485915,  1.        ,  0.         , 0.       ,   0.        ],
 [ 0.73900147, -3.06739299,  1.         , 0.       ,   0.        ],
 [-0.41936066,  2.07954916, -2.48001176,  1.       ,   0.        ],
 [ 0.8629648 , -5.26684888,  6.07259163, -2.00029337,  1.        ],
 [-0.39781133,  4.37513021,  1.95567188, -1.20511879,  2.90818423],
 [-1.23775551,  0.96738502, -6.00479805,  2.36192321, -6.35576004],
 [ 1.26812186, -6.24255548,  2.10212715, -0.22108135 , 0.78150706],
 [-2.21902784, 12.69620805, -3.64714684,  0.1774518 ,  3.02428501],
 [ 0.75872635, -6.54147509,  1.001566  , -0.1128815,  -1.35821625]]

X=np.array(X)
CE0=np.array(CE0)
print('n1,n2,p,r,n,Y,X,CE0:',n1,n2,p,r,n,Y,X,CE0)
d=min(n1+n2,r)
id=np.zeros(d,dtype=int) # initialization
id[:n1]=np.array(range(n1)) # the first n1 entries of Y are flag 1
print('id:',id)
iflag2=np.where(Y==2) # indices of flag 2 entries in Y
print('iflag2:',iflag2)
id[n1:d]=iflag2[0][:d-n1]
print('id:',id)

CE=np.hstack( ( CE0[:,:n1],X[:,id[n1:d]] ) ) # initialize CE as col echelon form of X
print('CE:',CE)
T=CE.T   # use EROs on the transpose, T=[U, *; V, W]
# reduce the lower left block of T corresponding to the first n1 cols
# to zero to get ET=[U, *; 0, Z] after EROs
ET=T # initialization
for j in range(n1):
    ETi=-ET[j,j:n]
    for i in range(n1,d):
         ET[i,j:n]=ETi*ET[i,j] + ET[i,j:n]
        
# now, ET=[U, *; 0, Z]
print('ET:',ET)
num_npr=0  # no. of new pivot cols
for i in range(n1,d): # first n1 rows of T are not changed
    if np.abs(ET[i,n1:n]).sum() > 1e-10: # if the row is not a zero row
        num_npr=num_npr+1
        jz=np.abs(ET[i,n1:n]).argmax()  # find the entry with largest magnitude to used as pivot entry
        jz=jz+1
        ET[i,n1:n]=ET[i,n1:n]/ET[i,jz] # make the pivot entry 1
        ETi=-ET[i,n1:n]
        for k in range(i+1,d):
            ET[k,n1:n]=ETi*ET[k,jz] + ET[k,n1:n] # EROs

        id[i]=-id[i]
        if num_npr==(r-n1):
            break  # exit i loop

print('id:',id)

n1,n2,p,r,n,Y,X,CE0: 2 2 5 5 10 [1 1 0 2 2] [[ 1.          0.          0.          0.          0.        ]
 [-0.35485915  1.          0.          0.          0.        ]
 [ 0.73900147 -3.06739299  1.          0.          0.        ]
 [-0.41936066  2.07954916 -2.48001176  1.          0.        ]
 [ 0.8629648  -5.26684888  6.07259163 -2.00029337  1.        ]
 [-0.39781133  4.37513021  1.95567188 -1.20511879  2.90818423]
 [-1.23775551  0.96738502 -6.00479805  2.36192321 -6.35576004]
 [ 1.26812186 -6.24255548  2.10212715 -0.22108135  0.78150706]
 [-2.21902784 12.69620805 -3.64714684  0.1774518   3.02428501]
 [ 0.75872635 -6.54147509  1.001566   -0.1128815  -1.35821625]] [[ 1.          0.          0.          0.          0.        ]
 [-0.35485915  1.          0.          0.          0.        ]
 [ 0.73900147 -3.06739299  1.          0.          0.        ]
 [-0.41936066  2.07954916 -2.48001176  1.          0.        ]
 [ 0.8629648  -5.26684888  6.07259163 -2.00029337  1.        ]
 [-0.39781

In [1]:

import numpy as np
n1,n2,p,r= 3, 1, 5, 5
id=np.array( [0,  1,  2, -4],dtype=int)
A0 = [[ 2.00000000e+00,  2.08251723e-01,  5.36956829e-01,  5.54034111e-01,
  -5.34962979e-01, -1.43319514e+00],
 [ 2.08251723e-01,  2.00000000e+00, -3.89212368e-02, -4.01675640e-01,
   5.52963246e-01,  2.43255144e+00],
 [ 5.36956829e-01, -3.89212368e-02,  2.00000000e+00,  2.35982121e-01,
  -6.26221819e-04, -1.40235114e+00],
 [ 5.54034111e-01, -4.01675640e-01,  2.35982121e-01,  2.00000000e+00,
  -5.43499357e-02, -1.62559567e+00],
 [-5.34962979e-01,  5.52963246e-01, -6.26221819e-04, -5.43499357e-02,
   2.00000000e+00,  3.02308269e+00]]
E0= [[ 1. ,         0.10412586 , 0.26847841,  0.27701706, -0.26748149, -0.71659757],
 [ 0. ,         1. ,        -0.04793589, -0.23220002 , 0.30766917 , 1.30504158],
 [ 0. ,         0.,          1.,          0.03522719,  0.09300353, -0.48280264],
 [ 0. ,         0.,          0.,          1.,          0.13185783, -0.34393003],
 [ 0.,          0.,          0.,          0.,          1.,          1.23647881]]

A0=np.array(A0)
E0=np.array(E0)

def updatelowerblock(A0):
    """ 
    Input:
    A0 = [U *; * *]
    Output:
    E0 = [U | rhs] is in rref
    """
    E0=A0  # initialization
    q=d+1  # no. of col of A0
    # reduce the lower block to zero for the first n1 cols
    for j in range(n1):
        E0i=-E0[j,j:q]
        for i in range(n1,d):
            E0[i,j:q]=E0i*E0[i,j] + E0[i,j:q]

    return E0

def backsub(n,num_piv,E,idx_piv):

    import numpy as np

    x = np.zeros((n,1)) # initialize
    for i in range(num_piv-1,-1,-1):
        #print('i:',i)
        sum=0
        for j in range(i+1,num_piv):
            #print('j:',j)
            sum = sum + E[idx_piv[i],idx_piv[j]]*x[idx_piv[j]]
            #print('sum:',sum)
        
        x[idx_piv[i]]=E[idx_piv[i],n] - sum
        #print('idx[i]:',idx_piv[i])
        #print('x:',x)

    return x

d=min(n1+n2,r)
cia=np.zeros(d,dtype=int) # initialization
cia[:n1]=np.array(range(n1)) # first n1 indices are flag 1
bool_idx_cia=np.ones(d,dtype=bool) # to discard indices of dependent cols
for j in range(n1,d):
    if id[j]<0:
        cia[j]=-id[j]
    else:
        d=d-1
        bool_idx_cia[j]=False
    
cia = cia[bool_idx_cia]
# drop the nonbasic cols correspond to flag 2 in the box and add RHS of the system [Q|d]
print('d:',d)
print('cia:',cia)
print('E0[:,cia]:',E0[:,cia])
print('E0[:,p]:',E0[:,p])
tempE=np.hstack( ( E0[:,cia],E0[:,p].reshape((-1,1))) ) 
# recycle the first n1 rows of E0 and add last r-n1 rows of A0
print('tempE[cia[:n1],:]:',tempE[cia[:n1],:])
print('cia[n1:d], np.concatenate((cia,[p])):',cia[n1:d],np.concatenate((cia,[p])))
     
if n1<d:
    #print('A0[cia[n1:d], np.concatenate((cia,[p])) ]:',A0[np.ix_(cia[n1:d], np.concatenate((cia,[p]))) ])
    E=np.vstack( (tempE[cia[:n1],:],  A0[np.ix_( cia[n1:d], np.concatenate((cia,[p]))) ]  ) )
    print('E:',E)
    E0=updatelowerblock(E)
else:
    E0=tempE[cia[:n1],:]

print('E0:',E0)
for j in range(n1,d):
        E0[j,j:(d+1)]=E0[j,j:(d+1)]/E0[j,j]
        print('E0:',E0)
        E0i=-E0[j,j:(d+1)]
        for i in range(n1+1,d):
            E0[i,j:(d+1)]=E0i*E0[i,j] + E0[i,j:(d+1)]
            print('E0:',E0)

print('E0:',E0)
xr=backsub(d,d,E0,range(d)) # back sub
xstar=np.zeros((p,1)) # initialization
xstar[cia]=xr

print('xstar:',xstar)




d: 4
cia: [0 1 2 4]
E0[:,cia]: [[ 1.          0.10412586  0.26847841 -0.26748149]
 [ 0.          1.         -0.04793589  0.30766917]
 [ 0.          0.          1.          0.09300353]
 [ 0.          0.          0.          0.13185783]
 [ 0.          0.          0.          1.        ]]
E0[:,p]: [-0.71659757  1.30504158 -0.48280264 -0.34393003  1.23647881]
tempE[cia[:n1],:]: [[ 1.          0.10412586  0.26847841 -0.26748149 -0.71659757]
 [ 0.          1.         -0.04793589  0.30766917  1.30504158]
 [ 0.          0.          1.          0.09300353 -0.48280264]]
cia[n1:d], np.concatenate((cia,[p])): [4] [0 1 2 4 5]
E: [[ 1.00000000e+00  1.04125860e-01  2.68478410e-01 -2.67481490e-01
  -7.16597570e-01]
 [ 0.00000000e+00  1.00000000e+00 -4.79358900e-02  3.07669170e-01
   1.30504158e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  9.30035300e-02
  -4.82802640e-01]
 [-5.34962979e-01  5.52963246e-01 -6.26221819e-04  2.00000000e+00
   3.02308269e+00]]
E0: [[ 1.          0.10412586  0.26