In [ ]:

import numpy as np
from scipy import linalg
import testalg

num_dim=1   # no. of examples of different dimensions
dim_egs=np.array([5, 20, 30])  # dimension of examples
num_data_pts=np.array([30, 50, 60])
num_k_values=1    
k_values=np.array([3, 4, 5]) 
s0_values=2*np.ones(num_dim,dtype=int) # no. of nonzero values in b0
num_instances=1           # no. of instances to run for each example
alg_flag=np.array([1, 1]) # =1 include in testing, =0 do not include  
num_alg=2
b0_type=1   # to generate the true coefficient vector b0

# initialize the arrays to save the final output
rss=np.zeros( (num_dim*num_k_values,num_alg) )
cpu_time=np.zeros( (num_dim*num_k_values,num_alg) )
num_iter=np.zeros( (num_dim*num_k_values,num_alg) )
stop_flag=-1*np.zeros( (num_dim*num_k_values,num_alg) )
for i in range(num_dim):

    p=dim_egs[i]
    n=num_data_pts[i]
    mu=np.zeros(p)
    sigma=np.eye(p)
    s0=s0_values[i]
    if b0_type==1: # example 1
        b0=np.zeros(p)
        i0=np.ceil(np.linspace(0,p,num=s0,endpoint=False)).astype(int) # get s0 evenly spaced indices, round the next integer if needed
        b0[i0]=1 
    elif b0_type==2: # example 2
        b0=np.zeros(p)
        b0[0:s0]=1 # make first s0 entries 1
    elif b0_type==3: # example 3
        b0=np.zeros(p)   
        i0 = np.random.randint(0,p,s0).astype(int) # pick s0 random indices to make nonzero
        j0 = np.random.randint(1,5,s0) # pick s0 random integers b/w 1 and 5
        b0[i0]=j0

    b0 = np.reshape(b0, (-1,1)) # make it a col array
    
    # run the algorithms and save the output
    for j in range(num_k_values): # for each k value, run the alg
        
        k = k_values[j]
        stop_flag_each_alg, cpu_time_each_alg, rss_each_alg=testalg.main(p,n,k,b0,mu,sigma,num_instances,num_alg,alg_flag)
        rss[j+i*num_k_values,:]=rss_each_alg
        cpu_time[j+i*num_k_values,:]=cpu_time_each_alg
        stop_flag[j+i*num_k_values,:]=stop_flag_each_alg

    # save the output in .pkl file
    print('rss:',rss)
    print('cpu:',cpu_time)
        
        

A,b,c: [[ 2.          0.47012747  0.4090279   0.34899272 -0.53074882]
 [ 0.47012747  2.          0.83474769 -0.22215772  0.17466388]
 [ 0.4090279   0.83474769  2.         -0.36060233  0.87273784]
 [ 0.34899272 -0.22215772 -0.36060233  2.          0.58575358]
 [-0.53074882  0.17466388  0.87273784  0.58575358  2.        ]] [[-0.63526821]
 [-0.38474006]
 [-0.24027198]
 [-1.23857424]
 [-0.75933276]] 2.9453397619274906
p,k= 5 3
x0,fx0: [[0.32350718]
 [0.        ]
 [0.        ]
 [0.46651321]
 [0.32888602]] 2.4288102621281937
ipiv0: [2 3 0 1 4]
ipiv1: []
npiv0, npiv00: 5 5
supp: [2 1 4]
Ahat: [[ 2.          0.34899272 -0.53074882]
 [ 0.34899272  2.          0.58575358]
 [-0.53074882  0.58575358  2.        ]]
bhat: [-0.63526821 -1.23857424 -0.75933276]
c: 2.9453397619274906
xout,fout: [[0.        ]
 [0.46651321]
 [0.32350718]
 [0.        ]
 [0.32888602]] 2.4288102621281933
xbest,fbest: [[0.        ]
 [0.46651321]
 [0.32350718]
 [0.        ]
 [0.32888602]] 2.4288102621281933
xlb : [[-0.07733803