In [1]:
import numpy as np
mu=np.array([0, 0, 0])
sigma=np.eye(3)
print(sigma)
seed=np.random.seed()
#rng = np.random.default_rng()
X = np.random.multivariate_normal(mu, sigma,10 )
print(np.shape(X))
print(X)
print(np.mean(X))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(10, 3)
[[ 0.98275124  0.36116724 -0.04531251]
 [-1.09112152 -1.0235868  -0.87823129]
 [-0.1723125   1.58433825 -0.75473487]
 [-0.71017318 -0.22518841 -1.26314325]
 [ 0.66063222 -0.04026144  1.95630459]
 [-0.37952248 -0.27506129 -0.64820628]
 [ 0.38658464  0.16049222 -0.28063663]
 [-0.06416386  0.36877904  1.76298866]
 [ 0.79383155 -0.87404126 -0.897905  ]
 [-1.16404884 -0.1783565  -1.19828243]]
-0.10488069011210592


To test the quadratic minimization while minimizing RSS in a least squares model.

In [1]:
import numpy as np
from conjgrad import cg
p=3
n=10
niter=1
for i in range(niter):
    mu=np.zeros(p)
    sigma=np.eye(p)
    seed=np.random.seed(i)
    X = np.random.multivariate_normal(mu, sigma,n )
    colmeans=np.mean(X,axis=0)  # find the mean of each column
    X= X - colmeans             # make the column mean zero
    colnorms = np.linalg.norm(X, axis=0, keepdims=True) # find 2-norm of each col
    X = X / colnorms 
    b = np.random.randint(-2,2,p)
    e = np.random.normal(size=n)
    y = X @ b.T + e.T
    
    A = 2*(X.T @ X)
    d = -2*(X.T @ y)
    c = y.T @ y

    # Perform spectral decomposition
    diagD, Qmat = np.linalg.eigh(A)  # diagD is a vector of eigenvalues in ascending order
                               # Qmat is orthonormal matrix of corresponding eigenvectors
    neig=sum(diagD>1e-9)    
    Q=Qmat[:,n-neig:]     
    D=diagD[n-neig:] 
    x=np.zeros(p)
    isNew, xnew, fxnew, niters, idExit=cg(p ,A ,d ,Q ,D ,neig ,x)
    print("isNew:",isNew)
    print("xnew:",xnew)
    print("fxnew:",fxnew)
    print("niters:",niters)
    print("idExit:",idExit)

iter: 0
x: [0. 0. 0.]
g: [-3.13014035  6.24964769  2.65485544]
h: [ 3.13014035 -6.24964769 -2.65485544]
55.9041323043392
xnew: [ 1.21337624 -2.42263067 -1.02913549]
iter: 1
x: [ 1.21337624 -2.42263067 -1.02913549]
g: [ 0.48872882  0.50565331 -0.61410696]
h: [-0.43992304 -0.60309907  0.57271192]
0.8716684874770957
xnew: [ 0.93670189 -2.80192892 -0.66894818]
iter: 2
x: [ 0.93670189 -2.80192892 -0.66894818]
g: [0.01449149 0.00174762 0.01297184]
h: [-0.01468394 -0.00201146 -0.0127213 ]
0.000381326180441352
xnew: [ 0.92849558 -2.80305305 -0.67605764]
isNew: 1
xnew: [ 0.92849558 -2.80305305 -0.67605764]
fxnew: -11.109625416812946
niters: 3
idExit: 0
