In [1]:
import numpy as np
mu=np.array([0, 0, 0])
sigma=np.eye(3)
print(sigma)
seed=np.random.seed()
#rng = np.random.default_rng()
X = np.random.multivariate_normal(mu, sigma,10 )
print(np.shape(X))
print(X)
print(np.mean(X))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(10, 3)
[[ 0.20097247  0.22093007  1.62751529]
 [-0.71183405  1.41201339 -0.03267171]
 [ 0.79363049 -2.62159823  0.4363773 ]
 [ 1.07970237  0.61105577 -0.77999884]
 [ 2.35817058 -1.8115023  -1.18849546]
 [-2.79431252  1.43008531 -0.51607595]
 [-1.19064852 -0.0884257  -1.77632339]
 [-0.56682813  0.75437922  0.06347197]
 [-2.1711898   0.72481729  0.51366566]
 [ 0.19220619 -0.60647498  2.03838595]]
-0.07996667451002722


To test the quadratic minimization while minimizing RSS in a least squares model.

In [ ]:
import numpy as np
from conjgrad import cg
p=3
n=10
niter=1
for i in range(niter):
    mu=np.zeros(p)
    sigma=np.eye(p)
    seed=np.random.seed(i)
    X = np.random.multivariate_normal(mu, sigma,n )
    colmeans=np.mean(X,axis=0)  # find the mean of each column
    X= X - colmeans             # make the column mean zero
    colnorms = np.linalg.norm(X, axis=0, keepdims=True) # find 2-norm of each col
    X = X / colnorms 
    b = np.random.randint(-2,2,p)
    e = np.random.normal(size=n)
    y = X @ b.T + e.T
    
    A = 2*(X.T @ X)
    d = -2*(X.T @ y)
    c = y.T @ y

    # Perform spectral decomposition
    diagD, Qmat = np.linalg.eigh(A)  # diagD is a vector of eigenvalues in ascending order
                               # Qmat is orthonormal matrix of corresponding eigenvectors
    neig=sum(diagD>1e-9)    
    Q=Qmat[:,n-neig:]     
    D=diagD[n-neig:] 
    x=np.zeros(p)
    isNew, xnew, fxnew, niters, idExit=cg(p ,A ,d ,Q ,D ,neig ,x)
    print("isNew:",isNew)
    print("xnew:",xnew)
    print("fxnew:",fxnew)
    print("niters:",niters)
    print("idExit:",idExit)

In [1]:
import heapq
h = []
heapq.heappush( h, (5, [1,0,1], [1.2, 2.2, 3.3]) )
heapq.heappush( h, (5, [1,0,0], [4.4, 5.2, 6.3]) )
heapq.heappush( h, (5, [1,1,1], [7.2, 8.2, 9.3]) )

#heapq.heappush(h, (1, 'write spec'))
#heapq.heappush(h, (3, 'create tests'))
item=heapq.heappop(h)

print(type(item[0]))
print(type(item[1]))
print(type(item[2]))


<class 'int'>
<class 'list'>
<class 'list'>
